import "dotenv/config";

export const {
  PORT,
  FE_URL,
  CLOUDINARY_NAME,
  CLOUDINARY_KEY,
  CLOUDINARY_SECRET,
  JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET,
  REDIS_URL,
  RAJAONGKIR_BASE_URL,
  RAJAONGKIR_API_KEY,
  ORIGIN_ADDRESS_ID,
  MIDTRANS_SERVER_KEY,
  MIDTRANS_CLIENT_KEY,
  NODEMAILER_USER,
  NODEMAILER_PASS
} = process.env;


